declare module 'lucide-react' {
  import { ComponentType, SVGProps } from 'react';
  
  export type LucideProps = SVGProps<SVGSVGElement> & {
    size?: string | number;
    absoluteStrokeWidth?: boolean;
  };
  
  export type LucideIcon = ComponentType<LucideProps>;
  
  // Export all icons as LucideIcon type
  export const Users: LucideIcon;
  export const BookOpen: LucideIcon;
  export const Target: LucideIcon;
  export const Trophy: LucideIcon;
  export const MessageSquare: LucideIcon;
  export const Brain: LucideIcon;
  export const TrendingUp: LucideIcon;
  export const TrendingDown: LucideIcon;
  export const BarChart3: LucideIcon;
  export const PieChart: LucideIcon;
  export const Activity: LucideIcon;
  export const Calendar: LucideIcon;
  export const Star: LucideIcon;
  export const CheckCircle: LucideIcon;
  export const Clock: LucideIcon;
  export const AlertTriangle: LucideIcon;
  export const AlertCircle: LucideIcon;
  export const Eye: LucideIcon;
  export const ArrowRight: LucideIcon;
  export const ArrowUpRight: LucideIcon;
  export const ArrowDownRight: LucideIcon;
  export const Filter: LucideIcon;
  export const Download: LucideIcon;
  export const Upload: LucideIcon;
  export const RefreshCw: LucideIcon;
  export const User: LucideIcon;
  export const UserPlus: LucideIcon;
  export const UserCheck: LucideIcon;
  export const UserX: LucideIcon;
  export const Mail: LucideIcon;
  export const Phone: LucideIcon;
  export const MessageCircle: LucideIcon;
  export const ExternalLink: LucideIcon;
  export const Zap: LucideIcon;
  export const Building2: LucideIcon;
  export const FileText: LucideIcon;
  export const FileX: LucideIcon;
  export const Shield: LucideIcon;
  export const Settings: LucideIcon;
  export const Plus: LucideIcon;
  export const Edit: LucideIcon;
  export const Trash2: LucideIcon;
  export const Save: LucideIcon;
  export const X: LucideIcon;
  export const Check: LucideIcon;
  export const Search: LucideIcon;
  export const DollarSign: LucideIcon;
  export const Percent: LucideIcon;
  export const TestTube: LucideIcon;
  export const HelpCircle: LucideIcon;
  export const ClipboardList: LucideIcon;
  export const Handshake: LucideIcon;
  export const Award: LucideIcon;
  export const Briefcase: LucideIcon;
  export const CreditCard: LucideIcon;
  export const ChevronDown: LucideIcon;
  export const ChevronLeft: LucideIcon;
  export const ChevronRight: LucideIcon;
  export const ChevronUp: LucideIcon;
  export const Menu: LucideIcon;
  export const Bell: LucideIcon;
  export const Home: LucideIcon;
  export const Folder: LucideIcon;
  export const File: LucideIcon;
  export const Image: LucideIcon;
  export const Video: LucideIcon;
  export const Music: LucideIcon;
  export const Link: LucideIcon;
  export const Copy: LucideIcon;
  export const Share: LucideIcon;
  export const Heart: LucideIcon;
  export const Bookmark: LucideIcon;
  export const Tag: LucideIcon;
  export const Flag: LucideIcon;
  export const MapPin: LucideIcon;
  export const Globe: LucideIcon;
  export const Wifi: LucideIcon;
  export const Battery: LucideIcon;
  export const Volume2: LucideIcon;
  export const VolumeX: LucideIcon;
  export const Play: LucideIcon;
  export const Pause: LucideIcon;
  export const SkipForward: LucideIcon;
  export const SkipBack: LucideIcon;
  export const Repeat: LucideIcon;
  export const Shuffle: LucideIcon;
  export const Lock: LucideIcon;
  export const Unlock: LucideIcon;
  export const Key: LucideIcon;
  export const LogIn: LucideIcon;
  export const LogOut: LucideIcon;
}